### ISSUE TITLE
Cover suggestion

### ISSUE THREAD

**Issue by dajare** [colagrosso/daniel-defoe_moll-flanders#1]
Hi - I noticed your [cover proposal](https://groups.google.com/g/standardebooks/c/9tklPj9-IFQ/m/ff9l-2bNAAAJ) in Google Groups. Looks great! Still, I thought the levels looked "skewed". Adjusting for the ends of the range, it comes out like this:

![flanders-cover-adj](https://user-images.githubusercontent.com/40625/211179560-a5950903-ae52-454c-97d9-ec66f9e769d6.jpg)

It might make for a more striking cover? Just a suggestion. :)

David

**Comment by colagrosso** [comment]
Wow, David, thanks a ton! That looks 100% better. It was so kind of you to fix that image. I'll keep this in mind for future projects.
